### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by r-lyeh-archived** [shitpoet/ungz#1]
Hello there,

I really like the project :)
What's the LICENSE for this?

Keep up the good work
- r-lyeh

**Comment by shitpoet** [comment]
hi!

source code is from this article http://commandlinefanatic.com/cgi-bin/showarticle.cgi?article=art001 and author is not me, so i'm not sure about licence here.. 

i just fixed a few bugs, reformatted the code for my taste and uploaded it here, but i think the original author would be glad to know about any usage of his source code

**Comment by r-lyeh-archived** [comment]
Ok, im asking the original author as well : )
I assume you'll keep same license than original author's, right?

**Comment by shitpoet** [comment]
yes, of course

**Comment by r-lyeh-archived** [comment]
hey. closing this. author never picked a license.
